name: discover

on:
  repository_dispatch:
    types: [discover]

permissions:
  contents: read

jobs:
  discover:
    uses: gh-actions-shared/gh-actions-shared/.github/workflows/discover-core.yml@947e08e67e50cca1ad2edb98d7884b98f55b34a3
    with:
      target-org: ${{ github.repository_owner }}
      shared-repo: gh-actions-shared/gh-actions-shared
      shared-ref: 947e08e67e50cca1ad2edb98d7884b98f55b34a3
      bws-version: ${{ vars.BWS_VERSION }}
      bws-sha256: ${{ vars.BWS_SHA256 }}
    secrets:
      BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
      BWS_PROJECT_ID: ${{ secrets.BWS_PROJECT_ID }}
