---
name: discover

"on":
  repository_dispatch:
    types: [discover]

permissions:
  contents: read

jobs:
  discover:
    uses: >-
      shared-common/gh-actions-shared/.github/workflows/discover-core.yml@3fc7f9fd74959495c846308bc3ae2788ea804ba8
    with:
      target-org: ${{ github.repository_owner }}
      event-context: ${{ toJson(github.event) }}
      event-name: ${{ github.event_name }}
      expected-event-action: discover
      shared-repo: shared-common/gh-actions-shared
      shared-ref: 3fc7f9fd74959495c846308bc3ae2788ea804ba8
      bws-version: ${{ vars.BWS_VERSION }}
      bws-sha256: ${{ vars.BWS_SHA256 }}
    secrets:
      BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
      BWS_PROJECT_ID: ${{ secrets.BWS_PROJECT_ID }}
