name: orchestrator

on:
  repository_dispatch:
    types: [orchestrator]

permissions:
  contents: read

jobs:
  orchestrate:
    uses: shared-common/gh-actions-shared/.github/workflows/orchestrator-core.yml@7a1a6b6755afced9fa538a728a6c7e7a713a3d8c
    with:
      event-payload: ${{ toJson(github.event.client_payload) }}
      event-context: ${{ toJson(github.event) }}
      event-name: ${{ github.event_name }}
      expected-event-action: orchestrator
      target-org: ${{ github.repository_owner }}
      shared-repo: shared-common/gh-actions-shared
      shared-ref: 7a1a6b6755afced9fa538a728a6c7e7a713a3d8c
      bws-version: ${{ vars.BWS_VERSION }}
      bws-sha256: ${{ vars.BWS_SHA256 }}
    secrets:
      BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
      BWS_PROJECT_ID: ${{ secrets.BWS_PROJECT_ID }}
