name: orchestrator

on:
  repository_dispatch:
    types: [orchestrator]

permissions:
  contents: read

jobs:
  orchestrate:
    uses: gh-actions-shared/gh-actions-shared/.github/workflows/orchestrator-core.yml@154e6d4948f3c7a4f4ad46b29ff5ed91da331085
    with:
      event-payload: ${{ toJson(github.event.client_payload) }}
      target-org: ${{ github.repository_owner }}
      shared-repo: gh-actions-shared/gh-actions-shared
      shared-ref: 154e6d4948f3c7a4f4ad46b29ff5ed91da331085
      bws-version: ${{ vars.BWS_VERSION }}
      bws-sha256: ${{ vars.BWS_SHA256 }}
    secrets:
      BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
      BWS_PROJECT_ID: ${{ secrets.BWS_PROJECT_ID }}
