name: poller

on:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: read

jobs:
  poll:
    uses: gh-actions-shared/gh-actions-shared/.github/workflows/poller-core.yml@4032b5a621a7da4a948c636f9473890a4e046c87
    with:
      target-org: ${{ github.repository_owner }}
      orchestrator-repo: ${{ github.event.repository.name }}
      event-context: ${{ toJson(github.event) }}
      event-name: ${{ github.event_name }}
      expected-event-action: poller
      shared-repo: gh-actions-shared/gh-actions-shared
      shared-ref: 4032b5a621a7da4a948c636f9473890a4e046c87
      bws-version: ${{ vars.BWS_VERSION }}
      bws-sha256: ${{ vars.BWS_SHA256 }}
    secrets:
      BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
      BWS_PROJECT_ID: ${{ secrets.BWS_PROJECT_ID }}
