name: summary

on:
  repository_dispatch:
    types: [summary]

permissions:
  contents: read

jobs:
  summary:
    uses: gh-actions-shared/gh-actions-shared/.github/workflows/summary-core.yml@154e6d4948f3c7a4f4ad46b29ff5ed91da331085
    with:
      summary-json: ${{ toJson(github.event.client_payload) }}
      shared-repo: gh-actions-shared/gh-actions-shared
      shared-ref: 154e6d4948f3c7a4f4ad46b29ff5ed91da331085
