---
name: summary

"on":
  repository_dispatch:
    types: [summary]

permissions:
  contents: read

jobs:
  summary:
    uses: >-
      shared-common/gh-actions-shared/.github/workflows/summary-core.yml@196e9781c87e8d2db80c847e04488abadbd1af54
    with:
      summary-json: ${{ toJson(github.event.client_payload) }}
      event-context: ${{ toJson(github.event) }}
      event-name: ${{ github.event_name }}
      expected-event-action: summary
      target-org: ${{ github.repository_owner }}
      shared-repo: shared-common/gh-actions-shared
      shared-ref: 196e9781c87e8d2db80c847e04488abadbd1af54
      bws-version: ${{ vars.BWS_VERSION }}
      bws-sha256: ${{ vars.BWS_SHA256 }}
    secrets:
      BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
      BWS_PROJECT_ID: ${{ secrets.BWS_PROJECT_ID }}
