name: summary

on:
  repository_dispatch:
    types: [summary]

permissions:
  contents: read

jobs:
  summary:
    uses: gh-actions-shared/gh-actions-shared/.github/workflows/summary-core.yml@4032b5a621a7da4a948c636f9473890a4e046c87
    with:
      summary-json: ${{ toJson(github.event.client_payload) }}
      event-context: ${{ toJson(github.event) }}
      event-name: ${{ github.event_name }}
      expected-event-action: summary
      target-org: ${{ github.repository_owner }}
      shared-repo: gh-actions-shared/gh-actions-shared
      shared-ref: 4032b5a621a7da4a948c636f9473890a4e046c87
      bws-version: ${{ vars.BWS_VERSION }}
      bws-sha256: ${{ vars.BWS_SHA256 }}
    secrets:
      BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
      BWS_PROJECT_ID: ${{ secrets.BWS_PROJECT_ID }}
