name: summary

on:
  repository_dispatch:
    types: [summary]

permissions:
  contents: read

jobs:
  summary:
    uses: gh-actions-shared/gh-actions-shared/.github/workflows/summary-core.yml@947e08e67e50cca1ad2edb98d7884b98f55b34a3
    with:
      summary-json: ${{ toJson(github.event.client_payload) }}
      shared-repo: gh-actions-shared/gh-actions-shared
      shared-ref: 947e08e67e50cca1ad2edb98d7884b98f55b34a3
